# Generated by Django 6.0.1 on 2026-01-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='google_map_link',
        ),
        migrations.AddField(
            model_name='place',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
